version: "3"
services:
  my_service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:8080
      - 5000:5000
    command: gunicorn --bind 0.0.0.0:5000 wsgi_debug:app