version: 2.1

jobs:
  test_test_and_deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Building services
          command: |
            ls
            docker-compose up -d
      - run:
          name: Running tests
          command: |
            docker-compose run my_service python ./tests.py
      - run: ssh-keyscan -H $AZURE_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy on test machine
          command: |
            ssh $AZURE_USER_NAME@$AZURE_HOST -p$AZURE_PORT /bin/bash \<<'\ENDSSH'
            sudo reboot
            \ENDSSH



workflows:
  version: 2
  test:
    jobs:
      - test_test_and_deploy:
          filters:
            branches:
              only: test
