version: 2.1

jobs:
  test_test_and_deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run:
          name: Building services
          command: |
            ls
            docker-compose up -d
      - run:
          name: Running tests
          command: |
            docker-compose run my_service python ./tests.py


workflows:
  version: 2
  test:
    jobs:
      - test_test_and_deploy:
          filters:
            branches:
              only: test
