version: 2.1

jobs:
  test_test_and_deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Building services
          command: |
            ls
            docker-compose up -d
      - run:
          name: Running tests
          command: |
            docker-compose run my_service python ./tests.py
      - run:
          name: Deploy on test machine
          command: |
            ssh $AZURE_USER_NAME@$AZURE_HOST -p$AZURE_PORT -y
            $AZURE_USER_PASSWORD
            cd cicd_circleci_prod_test/
            git checkout test
            git pull origin test
            docker-compose stop -t 1
            docker-compose up --build -d

workflows:
  version: 2
  test:
    jobs:
      - test_test_and_deploy:
          filters:
            branches:
              only: test
