version: 2.1

jobs:
  test_test_and_deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
#      - run:
#          name: Building services
#          command: |
#            ls
#            docker-compose up -d
#      - run:
#          name: Running tests
#          command: |
#            docker-compose run my_service python ./tests.py
#      - run: ssh-keyscan -H $AZURE_HOST >> ~/.ssh/known_hosts
#      - add_ssh_keys:
#          fingerprints:
#            - $AZURE_SSH_KEY_FINGERPRINT
      - run:
          name: Deploy on test machine
          command: |
            ls
            ssh $AZURE_USER_NAME@$AZURE_HOST "
            cd cicd_circleci_prod_test &&
            git checkout test &&
            git pull origin test &&
            sudo docker-compose stop -t 1 &&
            sudo docker-compose up --build -d
            "
workflows:
  version: 2
  test:
    jobs:
      - test_test_and_deploy:
          filters:
            branches:
              only: test
